proyect/app/models.py
import datetime

from . import db

class User(db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), unique=True, nullable=False)
    encrypted_password = db.Column(db.String(94), nullable=False)
    email = db.Column(db.String(100), unique=True, nullable=False)
    created_at = db.Column(db.DateTime, default=datetime.datetime.now())

def __str__(self):
    return self.username

proyect/app/forms.py
from wtforms import Form, StringField, PasswordField #, BooleanField,  validators
# stringfield convertira el texto en string y passwordfiel en tipo pass

from wtforms import validators

class LoginForm(Form):
    username = StringField('Username', [
        validators.length(min=4, max=20, message='El nombre de usuario tiene que ser mayor a 4 caracteres')
    ]) #reciben el label del form
    password = PasswordField('Password',[
        validators.Required()
    ])

proyect/app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap 
from flask_wtf.csrf import CSRFProtect # pip install Flask-WTF
from flask_sqlalchemy import SQLAlchemy

app = Flask(__name__)
db = SQLAlchemy()
csrf = CSRFProtect() # from flask_wtf.csrf import CSRFProtect
bootstrap = Bootstrap() # from flask_bootstrap import Bootstrap

from .views import page
from .models import User

def create_app(config):
    app.config.from_object(config)
    
    csrf.init_app(app)
    bootstrap.init_app(app) #iniciar boots
    app.register_blueprint(page) # from .views import page

    with app.app_context():
        db.init_app(app)
        db.create_all()

    return app

proyect/app/views.py
from flask import Blueprint
from flask import render_template, request

from .forms import LoginForm #importamos la clase definida en forms.py

page = Blueprint('page', __name__)

@page.app_errorhandler(404)
def page_not_found(error):
   return render_template('errors/404.html'), 404 # para renderisar paginas que no existen
   #se para el error , 404

@page.route('/')
def index():
   return render_template('index.html', title='Index')

@page.route('/about')
def about():
   return render_template('about.html', title='About')

@page.route('/login', methods=['GET', 'POST'])
def login():

   form = LoginForm(request.form) # se crea una nueva instancia de LoginForm
   #se pasa como argumento request.form que viene del formilario 

   if request.method == 'POST' and form.validate():
      #obtener los valores del form
      print(form.username.data)
      print(form.password.data)
      print('Nueva sesion')

   return render_template('auth/login.html', title='Login', form=form)

proyect/app/templates/about.html
{% extends 'layout.html' %}

{% block container %}
    <p>About</p>
{% endblock %}

proyect/app/templates/helpers/_forms.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <!-- <ul class=errors> -->
    {% for error in field.errors %}
    <p class='errors alert alert-danger mt-2'>{{ error }}</p>
      <!-- <li>{{ error }}</li> -->
    {% endfor %}
    <!-- </ul> -->
  {% endif %}
  </dd>
{% endmacro %}

proyect/app/templates/index.html
{% extends 'layout.html' %}

{% block container %}
    <p>Index Hola mundo</p>
{% endblock %}

proyect/app/templates/layout.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block navbar %} 
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{{ url_for('page.index')}}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('page.about')}}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('page.login')}}">Login</a>
        </li>
      </ul>
    </div>
  </nav>
{% endblock %}

{% block content %}
  <div class="container">
      <div class="row">
          {% block container %}
          {% endblock %}
      </div>
  </div>
{% endblock %}

{% block scripts %}
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
{% endblock %}